analysis: Fix CFG building with disconnected loops
Summary:
If a CFG somehow contains a disconnected loop (e.g. A->B->C->A where A
is not reachable from the entry point), getSources() will not find it
(because every node has in-degree > 0) and it won't get attached to the
virtual SOURCE node, causing errors in dominance computation like

    ghidra.util.exception.AssertException: No processed predecessors found for ffffffff8097bc8d
            at ghidra.graph.algo.ChkDominanceAlgorithm.computeDominance(ChkDominanceAlgorithm.java:119)
            at ghidra.graph.algo.ChkDominanceAlgorithm.<init>(ChkDominanceAlgorithm.java:81)
            at ghidra.graph.algo.ChkDominanceAlgorithm.<init>(ChkDominanceAlgorithm.java:67)
            at ghidra.graph.GraphAlgorithms.findDominanceTree(GraphAlgorithms.java:305)

Use getEntryPoints() instead, which returns sources as well as an
arbitrary vertex of each SCC.

Test Plan: ./scripts/analyze.sh kernel kernel.csv

Reviewers: oscar, ali

Reviewed By: ali

Differential Revision: https://review.rcs.uwaterloo.ca/D891