analysis: Fix bit-field storage size calculation
Calculating the byte width of a bit-field requires taking the bit offset
into account, not just the bit size:

    struct s {
            int a : 6;
            int b : 8;
            int c : 18;
    };

Field `b` would normally take up 1 byte, but due to its bit offset, it
takes up two bytes.  This was leading to errors like

    java.lang.IllegalArgumentException: Bitfield does not fit within specified constraints